### ISSUE TITLE
Problem with playing_time 

### ISSUE THREAD

**Issue by Juanpsd1224** [EugeneDae/VLC-Scheduler#9]
Hi, 

Thanks for creating VlcScheduler, It has very useful for me. Actually I'm having problems when I try to schedule an path folder, the program fails when I set this param on vlcscheduler.yaml config file. I'm running VlcScheduler on Raspberry Pi which uses Raspbian as operative system.

How can I solve this?

Regards

Traceback (most recent call last):
  File "vlcscheduler.py", line 199, in main
    loop.run_until_complete(main_coro())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "vlcscheduler.py", line 119, in main_coro
    primary_playlist.add_source(source)
  File "/home/pi/VLC-Scheduler-0.3.2/src/playlist.py", line 50, in add_source
    self._sources.append(self.prepare_source(source))
  File "/home/pi/VLC-Scheduler-0.3.2/src/playlist.py", line 43, in prepare_source
    in utils.parse_time_interval(source['playing_time'])
  File "/home/pi/VLC-Scheduler-0.3.2/src/utils.py", line 36, in parse_time_interval
    return match[1], match[2]
TypeError: '_sre.SRE_Match' object is not subscriptable

![Screenshot_71](https://user-images.githubusercontent.com/46231665/56473537-25648d80-6432-11e9-8458-3d35f40398cf.png)

![Screenshot_72](https://user-images.githubusercontent.com/46231665/56473555-72e0fa80-6432-11e9-9a61-9a925ba99592.png)

This how I config the YAML file

**Comment by EugeneDae** [comment]
I'm afraid VLC Scheduler is not compatible with older Python 3.5. 

Even if we fix SRE Match TypeError, it is likely we'll run into other problems later, because VLC Scheduler relies on a Python feature (called "asyncio") which is implemented differently in Python 3.6 than in Python 3.5.

I don't know if there are easy ways to have multiple versions of Python 3 installed simultaneously on Raspbian. On Ubuntu it is as simple as adding a deadsnakes ppa and running apt install python3.7

If you decide to upgrade the OS's default Python 3.5, do it on your own risk, because it can break things.

**Comment by Juanpsd1224** [comment]
I upgrade Python 3.7 and works perfecty...

Thanks a lot

**Comment by EugeneDae** [comment]
Glad it worked! Thanks for reporting back.
